name: Build

on:
  - workflow_dispatch
  - push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker build
        run: echo OK

